### PR TITLE
Stay on same page after performing action

### LINKED ISSUE #70: No longer staying on page after marking as read
OS: Arch Linux
Browser: Firefox 66.0.1
Notifications Preview for GitHub: 1.5.3

> Browser extension - Preview your notifications without leaving the page

This wonderful time-saver extension seems partly broken (due to recent GitHub changes?). I love previewing notifications `without leaving the page`, but recently I get `redirected` to https://github.com/notifications after marking stuff read. Is this something that can be fixed somehow?

### PR DESCRIPTION
**Pull request by tanmayrajani**
Closes #70 

- [x] Mark as read/unread/muted/unmuted
- [x] Code cleanup (~is it okay to keep a copy of `delegate-it` in `utils.js`~)
- [ ] Mark all as read
- [ ] Save for later (fails, uses GraphQL API)

### CODE REVIEW

File: extension/utils.js [hunk 1]
```diff
@@ -51,3 +51,109 @@ function sanitizeDOM(dom) {
...
+	// This will set the correct `origin` header without having to use XMLHttpRequest
+	// https://stackoverflow.com/questions/47356375/firefox-fetch-api-how-to-omit-the-origin-header-in-the-request
+	// https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#XHR_and_Fetch
+	const contentFetch = typeof window.content === 'object' ? window.content.fetch : window.fetch;
+	const formData = new FormData();
+	formData.append('utf8', '✓');
+	formData.append('authenticity_token', select('input[name="authenticity_token"]', form).value);
+
+	const response = await contentFetch(form.action, {
+		// TODO: drop `as` after https://github.com/microsoft/TSJS-lib-generator/issues/741
```
Comment (fregante) [inline extension/utils.js]:
```suggestion
```

File: extension/utils.js [hunk 2]
```diff
@@ -51,3 +51,109 @@ function sanitizeDOM(dom) {
...
+
+async function postForm(form) {
+	// `content.fetch` is Firefox’s way to make fetches from the page instead of from a different context
+	// This will set the correct `origin` header without having to use XMLHttpRequest
+	// https://stackoverflow.com/questions/47356375/firefox-fetch-api-how-to-omit-the-origin-header-in-the-request
+	// https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#XHR_and_Fetch
+	const contentFetch = typeof window.content === 'object' ? window.content.fetch : window.fetch;
+	const formData = new FormData();
+	formData.append('utf8', '✓');
+	formData.append('authenticity_token', select('input[name="authenticity_token"]', form).value);
```
Comment (fregante) [inline extension/utils.js]: You don't need this. This line already works:

```js
		body: new URLSearchParams(new FormData(form)),
```

File: extension/utils.js [hunk 3]
```diff
@@ -51,3 +51,109 @@ function sanitizeDOM(dom) {
 	}
 	return dom;
 }
+
+async function postForm(form) {
+	// `content.fetch` is Firefox’s way to make fetches from the page instead of from a different context
+	// This will set the correct `origin` header without having to use XMLHttpRequest
+	// https://stackoverflow.com/questions/47356375/firefox-fetch-api-how-to-omit-the-origin-header-in-the-request
+	// https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Content_scripts#XHR_and_Fetch
```
Comment (fregante) [inline extension/utils.js]: These comments can be dropped

File: extension/utils.js [hunk 4]
```diff
@@ -51,3 +51,109 @@ function sanitizeDOM(dom) {
 	}
 	return dom;
 }
+
```
Comment (fregante) [inline extension/utils.js]: Add

```js
// Pulled from: https://github.com/sindresorhus/refined-github/blob/9723b391d58ff29be41950b9c6c2ceca04e6b107/source/libs/post-form.ts
```

File: extension/utils.js [hunk 5]
```diff
@@ -51,3 +51,109 @@ function sanitizeDOM(dom) {
...
+	if (!response.ok) {
+		throw new Error(response.statusText);
+	}
+
+	return response;
+}
+
+const elements = new WeakMap();
+function _delegate(element, selector, type, callback, options) {
```
Comment (fregante) [inline extension/utils.js]: It's best to keep all of `delegate-it` into its own `delegate-it.js` file

Same for `post-form.js`

File: extension/index.js [hunk 6]
```diff
@@ -96,6 +98,28 @@ async function openDropdown({currentTarget: indicator}) {
 		const container = select('.NPG-dropdown', dropdown);
 		empty(container);
 		container.append(...list);
+
+		const forms = select.all(('.NPG-dropdown form'));
+		for (const form of forms) {
+			delegate(form, 'button', 'click', async event => {
```
Comment (fregante) [inline extension/index.js]: You don't need a `for` loop here. Use the snippet as suggested, without passing the `form` argument.

File: extension/index.js [hunk 7]
```diff
@@ -12,8 +12,10 @@ class Notifications {
 			this.dom = fetch(location.origin + url, {
 				credentials: 'include'
 			}).then(r => r.text()).then(parseHTML);
-		} catch (err) {/* Ignore network failures */}
+		} catch (err) {/* Ignore network failures */
+		}
```
Comment (fregante) [inline extension/index.js]: This change shouldn't be necessary.

**Comment by fregante** [comment]
> * Save for later (fails, uses GraphQL API)

If it fails, it fails. Don't complicate your life ✌️😅

File: extension/index.js [hunk 8]
```diff
@@ -96,6 +98,28 @@ async function openDropdown({currentTarget: indicator}) {
...
+				if (svgIconClassList.contains('octicon-primitive-dot')) {
+					issueNotificationParent.classList.replace('read', 'unread');
+				} else if (svgIconClassList.contains('octicon-check')) {
+					issueNotificationParent.classList.replace('unread', 'read');
+				} else if (svgIconClassList.contains('octicon-mute')) {
+					issueNotificationParent.classList.remove('unread');
+					issueNotificationParent.classList.add('muted', 'read');
+				} else if (svgIconClassList.contains('octicon-unmute')) {
+					issueNotificationParent.classList.remove('muted');
+				}
```
Comment (fregante) [inline extension/index.js]: Perhaps this, slightly shorter and relies on the form itself rather than the icon.

```js
const {form} = event.delegateTarget;
await postForm(form);

const notification = form.closest('.issue-notification');
if (form.matches('.js-mark-notification-as-read, .js-mute-notification')) {
	notification.classList.replace('unread', 'read');
} else if (form.matches('.js-mark-notification-as-unread')) {
	notification.classList.replace('read', 'unread');
}

if (form.matches('.js-mute-notification')) {
	notification.classList.add('muted');
} else if (form.matches('.js-unmute-notification')) {
	notification.classList.remove('muted');
}
```

Comment (tanmayrajani) [reply extension/index.js]: Did so, it definitely is a better way. 

Also, changed the following
```js
if (form.matches('.js-mute-notification')) {
	notification.classList.add('muted');
```
to be
```js
if (form.matches('.js-mute-notification')) {
	notification.classList.add('muted', 'read');
```
to make it consistent with how it works on `/notifications` page when we mute a notification

**Comment by tanmayrajani** [comment]
Thanks so much for your inputs @fregante. Code looks much cleaner now. 

Even if we let "save for later" go for now, I think we should do something about "mark all as read" at least? WDYT?

Or, should we merge this at least and then look into other pending things?

**Comment by sfdye** [comment]
It will be great if we can get the "stay on same page" behavior back, then the new features :)
